name: create package on release

on:
    release:
        types: [created]

jobs:
    build_package_and_release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: create deb package
              run: dpkg-deb --build ./package

            - name: upload release assets
              uses: softprops/action-gh-release@v2
              with:
                tag_name: ${{github.event.release.tag_name}}
                files: "${{github.workspace}}/builds/*"

