name: publish
on:
  release:
    types: published
  workflow_dispatch:
    inputs:
      release_tag:
        required: true
        description: the tag to release for
        default: ""
jobs:
  release_bin:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - run: make compile
      - run: echo "FNAME=coinflip-$(uname -s)-$(uname -m)" >>"$GITHUB_ENV"
      - run: mv bin/coinflip "$FNAME"
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{github.event.release.tag_name || github.event.inputs.release_tag}}
          files: ${{env.FNAME}}
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - if: ${{env.ACT}}
        uses: actions/upload-artifact@v4
        with:
          path: ${{env.FNAME}}
