name: validate
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make compile
